# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name f3
#' @title Generate Random Numbers from Uniform Distribution
#' @description This function generates a matrix of random numbers drawn from a uniform distribution between 0 and 100
#' @param num An integer specifying the number of random numbers to generate
#' @return A NumericMatrix of size \code{num x 1}, where each element is a random number between 0 and 100
#' @examples
#' \dontrun{
#' # Generate 5 random numbers between 0 and 100
#' random_numbers <- f3(5)
#' print(random_numbers)
#' }
#' @export
f3 <- function(num) {
    .Call('_SA24204171_f3', PACKAGE = 'SA24204171', num)
}

